#!/usr/bin/env ruby
# Requires: Summary.xml, run from main directory (which includes fmp_{clone,ddr,text}/)

require 'fmpvc'
include FMPVC

time_start = Time.new

ddr_dir = './fmp_ddr'
ddr = DDR.new(ddr_dir)
ddr.process_reports
ddr.write_reports

# create a tree file, if available
require 'mkmf'
module MakeMakefile::Logging
  # don't let MakeMake leave extraneous logs
  @logfile = File::NULL    
end 
tree_command = find_executable 'tree'
if tree_command
   puts "Creating tree.txt."
   `#{tree_command} -F > tree.txt`
end

time_end = Time.new
puts "Processing complete."  
puts "Elapsed time: #{(time_end - time_start).round(0)} seconds."

puts


