#!/usr/bin/env ruby
# Requires: Summary.xml, run from main directory (which includes fmp_{clone,ddr,text}/)

require 'fmpvc'
include FMPVC

# create a DDR
print "Create new DDR..."
ddr_dir = './fmp_ddr'
ddr = DDR.new(ddr_dir)
puts "done."

# process FMPReport files
print "Create FMPReports..."
ddr.process_reports
puts "done."

# write them to disk
print "Write reports to disk..."
ddr.write_reports
puts "done."

# create a tree file
require 'mkmf'
module MakeMakefile::Logging
  # don't let MakeMake leave extraneous logs
  @logfile = File::NULL    
end 
tree_command = find_executable 'tree'
if tree_command
   puts "Creating tree.txt..."
   `#{tree_command} -F > tree.txt`
end

puts


